blank_issues_enabled: false
contact_links:
  - name: Steam Community Hub
    url: https://steamcommunity.com/app/2877660
    about: Visit the Steam Community Hub for general discussions and community content
  - name: Jitter on Steam
    url: https://store.steampowered.com/app/2877660/Jitter/
    about: Visit the official Steam store page for Jitter
